### ISSUE TITLE
Propose to update help sites for En/Ru

### ISSUE THREAD

**Issue by JxhnnyUt8h** [obsidianmd/obsidian-docs#165]
Hello,

I propose to update Help sites for English and Russian, and maybe for other languages, if need.
As I can see, some published notes are outdated and don't match the latest GitHub versions.

Thanks.

**Comment by henrikfalk** [comment]
@JxhnnyUt8h  I totally agree :)

I have asked if the release process could include documentation for every new version. I also meant the web-version.
Because of three reasons:
1. Serious users that have not tried the software yet often browse the documentation to see if it have the features that fits the user needs. If the docs is not updated you loose potential customers especially because Obsidian evolves so quickly
2. I have used many hours to translate the documentation for free into my native language to support Obsidian even though I am happy with an English version. If the docs are only released randomly and seldom I feel that my work have low priority
3. I often get questions about Obsidian that users could have read themselves if they had access to the newest docs. 

I know it's a very small development team and translations have not always top priority compared to features. But if docs (app+web) could be updated monthly at least it would be great :)

**Comment by ericaxu** [comment]
Sorry about that, we can try to update the online docs more often.

In-app docs are trickier, because of the insider process, the public version is almost always delayed by 2 weeks or sometimes even more.

**Comment by yo-goto** [comment]
Plz update Ja docs too for mobile apps. It seems so outdated🥺

**Comment by ericaxu** [comment]
Published ru/da/ja. Sorry about the wait!

**Comment by JxhnnyUt8h** [comment]
@ericaxu thank you! Could you please also add [Русский](https://publish.obsidian.md/help-ru) and [Tiếng Việt](https://publish.obsidian.md/help-vi) to English Help [Index](https://help.obsidian.md/Index) page.

**Comment by marcusolsson** [comment]
Looks like we can close this issue as the languages have been published/added? As for the original post, if there are outdated docs, let's create an issue for each occurrence?
