### ISSUE TITLE
Heading and block embeds are undocumented

### ISSUE THREAD

**Issue by colintedford** [obsidianmd/obsidian-docs#301]
The [embed page](https://help.obsidian.md/How+to/Embed+files) doesn't mention that one can use the heading link and block link syntax to embed parts of notes.

The [embed notes section](https://help.obsidian.md/How+to/Embed+files#Embed+notes) ends in a trailing colon, so maybe the missing info was accidentally deleted or there was a copy-paste error or something.

**Comment by marcusolsson** [comment]
Documentation for embedding resources exists in multiple places right now:

- Embed notes: https://help.obsidian.md/How+to/Embed+files#Embed+notes
- Embed headings: https://help.obsidian.md/How+to/Internal+link#Link+to+headings
- Embed blocks: https://help.obsidian.md/How+to/Link+to+blocks#Embed+or+transclude+blocks

The embed notes section embeds Accepted file formats (as an example), which is why it looks like there's nothing after the colon.

There's definitely opportunity to improve discoverability here though.
