### ISSUE TITLE
Question - Danish help

### ISSUE THREAD

**Issue by grawsom** [obsidianmd/obsidian-docs#383]
Any other in the process of translation some of the rest help into Danish.
It's more so we don't do double work

**Comment by henrikfalk** [comment]
Yes, I am. I am the one who translated the initial docs into Danish. For a long period we were not advised to translate due to the many changes but now it is ok again.
You are welcome to help translating when I have committed the parts I have already done. We can divide the rest between us or something.
You can contact med directly via my email in my profile.

**Comment by grawsom** [comment]
@henrikfalk - I will keep an eye for this

**Comment by henrikfalk** [comment]
> @henrikfalk - I will keep an eye for this

@grawsom
I just made a formal pull request for the Danish translation to notify that I am working on it.

**Comment by grawsom** [comment]
> > @henrikfalk - I will keep an eye for this
> 
> @grawsom I just made a formal pull request for the Danish translation to notify that I am working on it.

@henrikfalk 
It's my first time working on a project, how do I go on from here -
